### ISSUE TITLE
Unable to use compute ssh

### ISSUE THREAD

**Issue by ben-joostens** [digitalocean/action-doctl#14]
`doctl compute ssh` is throwing te following error:
    
    $ doctl compute ssh $DROPLET_ID --ssh-command pwd
    Warning: Identity file /root/.ssh/id_rsa not accessible: No such file or directory.
    Host key verification failed.

I'm currently using ```digitalocean/action-doctl@v1.5.0```

I've tried a few workarounds like generating the key, but I can't get it going. At first I thought I was running into this issue: https://github.com/digitalocean/doctl/issues/263 but I don't think they're related as snap is not involved in this action as far as I'm aware, not to mention it was fixed a while ago.

**Comment by andrewsomething** [comment]
In order to SSH into a Droplet, `doctl` needs access to the private half of the SSH key pair whose public half is on the Droplet. Currently the `doctl` Action is based on a Docker container. If you were using the Docker container directly, you could invoke it with:

```
docker run --rm --interactive --tty \
  --env=DIGITALOCEAN_ACCESS_TOKEN=<YOUR-DO-API-TOKEN> \
  -v $HOME/.ssh/id_rsa:/root/.ssh/id_rsa \
  digitalocean/doctl compute ssh <DROPLET-ID>
```

in order to mount the SSH key from outside the container.

You might be better off just using `doctl` to grap the Droplet's IP address and using this Action that is more focused on SSH related use cases and provides a lot of additional functionality: https://github.com/marketplace/actions/ssh-remote-commands

**Comment by ben-joostens** [comment]
Ah, I see, I was hoping that there were no keys involved since it requires an access token. In fact, that was exactly why I was trying to use it. Thanks for the suggestion, I'll switch to an SSH action.
